name: My Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read   # Allows access to repository content (if needed)

    steps:
    # Azure Login       
    - name: Login to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Use the secret for the client ID
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Use the secret for the tenant ID
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Use the secret for the subscription ID
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/dc2b1a3b-1f25-405f-a2ed-e8bdbbf14c83/resourceGroups/rg-avd-Test
